### PR TITLE
Large refactor & feature additions (multi-stack + mixed + tabs + pawn choice) & performance improvement

### PR DESCRIPTION
**Pull request by abrenneke**
Hey @Syrchalis!

This started as simply working to add a multi-stack feature, but progressed into some huge changes and feature additions for the mod. I know it's a lot to check, but I would love if all this got into the existing mod rather than me having to create another fork!

# Features

## Multi-Stack Support
A single fermenter can have multiple stacks of items which each start processing at the moment the stack is inserted. For example, if you have a kiln with 25/50 bricks in it half done, and you add another 25 bricks, then the existing 25 bricks will still be half done, and the second stack will be 0% done. This makes UF much more versatile in what mods can use it!

Multi-stack is applied when a process has `<processType>Multiple</processType>` or `<processType>MultipleMixed</processType>`. The default is still `<processType>Single</processType>`, which is valid for liquid-type fermentation.

image

## Mixed Processing Support
If `<processType>MultipleMixed</processType>` is set for a process, then other `MultipleMixed` processes can be running at the same time! For example, you could have an oven which could bake bread and pizza at the same time!

* `MultipleMixed` is good for things like ovens, that can process different unrelated things at the same time.
* `Multiple` is good for things like the drying racks shown above, where the texture changes based on the item inserted. 

## Pawns Choose Product
A single fermenter is no longer assigned a single process. There is a new `Product` tab, which lets you choose the products that the fermenter will create. Then, the pawns can decide what to put in that fermenter, based on the filter you've selected. Defaults to all processes supported by the fermenter, and is hidden if there is only one process!

image

## Ingredient Filter
You can choose the ingredients that can be used for the fermenter in the Filter tab, such as only ingredients below a certain HP percent, or not using rotten ingredients.

image

## Contents Tab
A new tab shows the contents of the fermenter, what they will turn in to, the target quality, the current speed, and the current finished percent! Tooltips on all the columns show even more detailed information.

image

## Support for `CompRefuelable.consumeFuelOnlyWhenUsed`
If `consumeFuelOnlyWhenUsed=true`, then the fermenter will only consume fuel while it has ingredients inserted. Empty fermenters will not consume fuel.

## Performance Improvements
I've run a profiler on the game and optimized everything in UF which was taking a lot of time. The performance was already good, but this improves it even more.

## Seamless Upgrade
Existing fermenters in a save will update to the new save format automatically. 

## C# 9 Update
Solution has been upgraded to the latest C# 9 (you may have to install the beta)

I hope you'll be able to check this out soon!

### CODE REVIEW

**Comment by abrenneke** [comment]
I found some bad performance interactions with other mods, looking into it.

**Comment by abrenneke** [comment]
Okay, that performance issue has been fixed. Down to 0.2% of time taken in UF.

**Comment by abrenneke** [comment]
Hi @Syrchalis have you had a chance to look at this? I know it's a lot, I apologize! I've been fixing bugs I find as I've been playing the game.

**Comment by GuardianDll** [comment]
Wow, looks like a real good update. Sadly looks like original author abandon modding :'(

**Comment by abrenneke** [comment]
Yeah it's a shame @GuardianDll, I'll probably get this fork onto the workshop at some point.

**Comment by GuardianDll** [comment]
One question for you, if youre not busy: when i apply your version of mod, my fermenter got error, cause i have few different recipes with own ingredients and efficiency, but with the same thingDef, and its broke my fermenter with error:
```
Could not instantiate or initialize a ThingComp: System.ArgumentException: An item with the same key has already been added. Key: Nitre
  at System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) [0x000c1] in <567df3e0919241ba98db88bec4c6696f>:0 
  at System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) [0x00000] in <567df3e0919241ba98db88bec4c6696f>:0 
  at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement] (System.Collections.Generic.List`1[T] source, System.Func`2[T,TResult] keySelector, System.Func`2[T,TResult] elementSelector, System.Collections.Generic.IEqualityComparer`1[T] comparer) [0x0002d] in <351e49e2a5bf4fd6beabb458ce2255f3>:0 
  at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] keySelector, System.Func`2[T,TResult] elementSelector, System.Collections.Generic.IEqualityComparer`1[T] comparer) [0x00066] in <351e49e2a5bf4fd6beabb458ce2255f3>:0 
  at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] keySelector, System.Func`2[T,TResult] elementSelector) [0x00000] in <351e49e2a5bf4fd6beabb458ce2255f3>:0 
  at UniversalFermenter.CompUniversalFermenter.Initialize (Verse.CompProperties props) [0x00010] in <6202cf1ac201498b8bc9e78a89f89726>:0 
  at (wrapper dynamic-method) Verse.ThingWithComps.Verse.ThingWithComps.InitializeComps_Patch1(Verse.ThingWithComps)
```
do you know how to fix it?

**Comment by abrenneke** [comment]
@GuardianDll from that error, it looks like the recipe for Nitre got added twice somehow, you'll probably want to hunt through all the patches or write another patch to remove the duplicate.

**Comment by GuardianDll** [comment]
Its not a bug, its a feature - i make recipe of nitre from dead bodies (with one efficiency), and another from rotten meat (with another efficiency, cause usually you have more rotten meat than dead bodies). I cant put them into one recipe, cause game cant realise that 1 dead body must cost more than 1 rotten meat, so player left with choise: make 2 nitre from 2 body or make 2 nitre from 2 rotten meat(technically 45 times more efficent). Thats why i made few recipes with one same resource for producing.

**Comment by Syrchalis** [comment]
I will implement this, or a part of it, when I get to it, I don't have time currently.

Before I can do it I have to properly understand the code though - I can't modify my code to something I dont fully understand, otherwise it'll lead to trouble down the line, so it will be a while.

**Comment by abrenneke** [comment]
Oh dang didn't expect you to do anything with this @Syrchalis - been a while since I did rimworld modding but let me know if you have any questions!

**Comment by Syrchalis** [comment]
> Oh dang didn't expect you to do anything with this @Syrchalis - been a while since I did rimworld modding but let me know if you have any questions!

Yes actually. There is a few bugs.

First bug is if you disable all products. Then enable one, let a pawn start the job (aka he moves to ingredient to haul it to the barrel) then disable the product again he'll attempt to fill it, finish, barrel stays empty and ingredient is lost
If you disable the product later in the job (cant remember when exactly) its even worse
I think its when you do it during the filling
Then the pawn will grab ALL WORT he can find and try to shove it into the barrel and it'll all just disappear

Second bug I struggle to do a proper reproduction. However when testing with 2 products, disabling all products and re-enabling the first in the list (happened with beer but not my blueberry wine?) pawns wont get the option to fill barrels. Despite all ingredients being checked and a product being checked they can't fill the barrel at all.

I'll open issues for this.

**Comment by abrenneke** [comment]
That sounds familiar, it's probably hitting one of the edge case error handling cases and just deleting the invalid item instead of dropping it on the ground. I'll try to check out the code again tonight :v:

**Comment by Syrchalis** [comment]
I decided to rewrite the mod. I really love the changes you made and the ideas of them, but I believe you're just a bit too much above my level in coding and I struggle to maintain my mod and fix bugs with that code.

So I rewrote the code almost from scratch under https://github.com/Syrchalis/ProcessorFramework.

It adds all the features you added. I took your code as inspiration and improved on the UI (combined ingredient/product tab into one) and added more logic. I can't do all the caching you did, but performance testing showed that it's still way way below your average mod. The biggest spikes come from WorkGiver/JobDriver anyway with ~2ms and average impact <0.01ms.

Your strings and the content tab I mostly copied without many changes, I hope you are okay with that.



The ITab shows no matter how many processors are selected (as long as they are the same type), allowing directly editing many things at once, without the need for copy/paste. It is 4 clicks instead of 6. As a designer, I love that.

The only thing my mod can't do at the moment is quality. The functionality is there basically, but I haven't figured out a decent enough implementation yet, particularly UI-wise.

**Comment by abrenneke** [comment]
That's awesome @Syrchalis! Don't worry about my code, I'm just glad it was an inspiration of sorts! I'll take a look as soon as I can! I love that gif!

**Pull request merged**
